spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: s-crs@outlook.com
    password: Agnus21@
    properties:
      mail:
        from: s-crs@outlook.com
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

#    username: cristian.s@inbox.ru
#    password: mtewu1qta7bYPXf6TBQg
  #  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/usm
    username: postgres
    password: 2121
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true